title: "Duvier Suarez Fontanella"
description: "Academic website of Duvier Fontanella"
url: "https://duviersuarezfontanella.es"
baseurl: ""

author:
  name: "Duvier Fontanella"
  role: "PhD Candidate in Theoretical and Computational Astrophysics"
  affiliation: "Department of Fundamental Physics and Mathematics, University of Salamanca"
  email: "duvier@usal.es"
  github: "Du92"

collections:
  research:
    output: true
    permalink: /research/:name/
  software:
    output: true
    permalink: /software/:name/
  outreach_transfer:
    output: true
    permalink: /outreach-transfer/:name/
  notes:
    output: true
    permalink: /notes/:name/

markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - vendor/
  - .bundle
  - .bundle/
  - .git
  - .gitignore
  - _site
  - _site/
  - .jekyll-cache
  - .jekyll-cache/
  - .jekyll-metadata
